### ISSUE TITLE
status fragt nicht alle Variablen ab

### ISSUE THREAD

**Issue by Chriss122** [Heckie75/eQ-3-radiator-thermostat#24]
Hallo zusammen,

mir werden leider nicht alle Variablen beim stauts Befehl zurückgegeben, ich wollte mal nachfragen ob jemand ähnliches hat oder mir helfen kann ?

<code>/var/www/html/eq/eq3.exp 00:1A:22:10:71:C8 status

Temperature:                    25.0°C
Valve:                          100%
Mode:                           manual dst
Vacation mode:                  off

can't read "d": no such variable
    while executing
"return $d"
    (procedure "hexToDecimal" line 3)
    invoked from within
"hexToDecimal [lindex $raw_timer [expr 2 * $event + 1 ]]"
    (procedure "readTimer" line 13)
    invoked from within
"readTimer $day"
    (procedure "readTimers" line 5)
    invoked from within
"readTimers"
    (procedure "init" line 14)
    invoked from within
"init [expr $INIT(device) + $INIT(mode) + $INIT(timer) + $INIT(serial)]"
    ("^status$" arm line 2)
    invoked from within
"switch -regexp $c {
    ^sync$ {
      init $INIT(mode)
    }
    ^comforteco.* {
      checkArgs $c 2 "comforteco" {^comforteco [0-9]{1,2}\.?[05]? [0..."
    (procedure "doCommand" line 10)
    invoked from within
"doCommand"
    (file "/var/www/html/eq/eq3.exp" line 1157)
</code>

Der Pfad ist nicht entscheidend, diesen hab ich bewusst geändert. 
Auch im Standard Pfad erhalte ich den selben Fehler.
Timer "wed" ist hinterlegt so wie im "Tutorial"
lässt sich auch über den Status timer wed auslesen:
<code>/var/www/html/eq/eq3.exp 00:1A:22:10:71:C8 timer wed

Timer for Wed:
        Wed, 00:00 - 05:00:     20.0°C

        Wed, 05:00 - 06:30:     24.0°C

        Wed, 06:30 - 16:30:     19.0°C

        Wed, 16:30 - 23:00:     24.0°C

        Wed, 23:00 - 24:00:     20.0°C
</code>

VG
Chriss

**Comment by Heckie75** [comment]
Hallo,

dieses Problem tritt meistens auf, wenn die Verbindung zu dem Bluetooth-Thermostat schlecht ist, also ein Problem der Reichweite. 

Viele Grüße
