### ISSUE TITLE
eq3 radiator thermostat with Blynk app

### ISSUE THREAD

**Issue by maciekelga** [Heckie75/eQ-3-radiator-thermostat#28]
Hi,
I want to ask if it is possible to control thermostats via Blynk application?

**Comment by JacekKac** [comment]
if you are talking about https://blynk.io/ - this is a library which need to be installed on a host hardware like raspberry pi so if you can operate it from host computer you will be able to do it also from this app. 
The app will not be able to operatore directly which eq3 - it's not indended to do so. 
J
