### ISSUE TITLE
Specify bluetooth interface

### ISSUE THREAD

**Issue by JsBergbau** [Heckie75/eQ-3-radiator-thermostat#30]
If you change line
`spawn -noecho /usr/bin/gatttool -I `
to
`spawn -noecho /usr/bin/gatttool -I -i hci1` you can use it with another interface.

Would be great to do it dynamically from command line. A good place would be the last argument like
`eq3.exp aa:bb:cc:dd:ee:ff boost hci1`

However I'm not a expect/tcl expert and not used to the logic of this script. 
I've changed the line in parse args
```
  set cmd ""
  for {set i 1} {$i < [llength $argv]} {incr i} {
    if {$i > 1} {
      append cmd " "
    }
    if {[regexp -nocase "hci" [lindex $argv $i]]} {
      puts "Store interface in a global variable here"
    } else  {
      append cmd [lindex $argv $i]
    }
  }
```
However then doCommand does another check and fails. You as developer should be able to change it in a few minutes.

Thanks for help.

**Comment by Heckie75** [comment]
Done. Pls check latest version.
