### ISSUE TITLE
Auslesen der Timer-Werte mit "timer-settings" bricht mit Fehler ab

### ISSUE THREAD

**Issue by MartinJ-de** [Heckie75/eQ-3-radiator-thermostat#40]
Erstmal Danke für das Tool, erspart eine Menge Gefummel!

Ich habe an meinem Test-Termostat (MAC-Adresse xxx) die Zeiten neu gesetzt:

pi$ eq3.exp xxx timer everyday 5.0 00:00 8.0 24:00

Status gibt zurück:

pi$ eq3.exp xxx status

Temperature:			4.5°C
Valve:				0%
Mode:				off
Vacation mode:			off

Comfort temperature:		21.0°C
Eco temperature:		17.0°C

Open window temperature:	12.0°C
Open window time:		00:15

Offset temperature:		0.0°C

Timer for Thu:
	00:00 - 00:00:	5.0°C
	00:00 - 24:00:	8.0°C

Timer for Fri:
	00:00 - 00:00:	5.0°C
	00:00 - 24:00:	8.0°C

Timer for Sat:
	00:00 - 00:00:	5.0°C
	00:00 - 24:00:	8.0°C

Timer for Sun:
	00:00 - 00:00:	5.0°C
	00:00 - 24:00:	8.0°C

Timer for Mon:
	00:00 - 00:00:	5.0°C
	00:00 - 24:00:	8.0°C

Timer for Tue:
	00:00 - 00:00:	5.0°C
	00:00 - 24:00:	8.0°C

Timer for Wed:
	00:00 - 00:00:	5.0°C
	00:00 - 24:00:	8.0°C

Device mac:			xxx
Device name:			CC-RT-BLE
Device vendor:			eq-3

Timer-Settings abfragen geht schief:

pi$ eq3.exp xxx timer-settings

can't read "thermostat("timer_start_0_3")": no such element in array
    while executing
"if {"00:00" == "$thermostat("timer_start_$key")"} {
      append out "$thermostat("timer_temperature_$key") "
      continue
    }"
    (procedure "dumpTimer" line 10)
    invoked from within
"dumpTimer $day"
    (procedure "dumpTimers" line 4)
    invoked from within
"dumpTimers"
    ("^timer-settings$" arm line 3)
    invoked from within
"switch -regexp $c {
    ^sync$ {
      init $INIT(mode)
    }
    ^comforteco.* {
      checkArgs $c 2 "comforteco" {^comforteco [0-9]{1,2}\.?[05]? [0..."
    (procedure "doCommand" line 10)
    invoked from within
"doCommand"
    (file "/usr/local/bin/eq3.exp" line 1265)

**Comment by Heckie75** [comment]
Hallo,

ich kann den tatsächlich nicht reproduzieren. Die obige Einstellung des Timers finde ich aber merkwürdig wie man schon an der Ausgabe sieht, da es ja heißt, dass die 5°C effektiv nicht gesetzt werden. Probiere, dass Ziel zu erreichen, in dem mind. zwei Zeiträume mit den 8°C gesetzt sind.

Viele Grüße
Martin
